# Generated by Django 5.2.14 on 2026-05-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bmihistory_chatbothistory_predictionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmihistory',
            name='weight',
        ),
    ]
